Greeting = ["hello", "hi", "hey", "howdy", "morning", "afternoon", "evening", "night"]
Farewell = ["goodbye", "bye", "later", "got to go", "see you", "farewell"]
Time = ["time"]
Date = ["date", "day of the week"]
Google = ["google", "search", "internet"]
Youtube = ["youtube"]
Mipt = ["mipt", "university"]
Github = ["github"]
